spring:
  application:
    name: product
  datasource:
    password: 
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dolores?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 47.98.140.228
    port: 6379
    jedis:
      pool:
        max-active: 10 #连接池最大连接数，负数表示没有限制
  server:
    port: 8088
env: dev
