spring:
  application:
    name: gateway
  redis:
    port: 6379
    host: 47.98.140.228
    jedis:
      pool:
        max-active: 10
server:
   port: 9000
env: dev
zuul:
  routes:
    Myproduct:
      path: /Myproduct/**
      serviceId: PRODUCT
  sensitive-headers:
management:
  security:
    enabled: false
