spring:
  application:
    name: order
  datasource:
    password: 
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dolores?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://47.98.140.228:8762/eureka/
server:
  port: 8082
env: dev
