env: debug
server:
  port: 8083
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://127.0.0.1:3306/dolores?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
