spring:
  application:
    name: product
  datasource:
    password: 
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dolores?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8082
env: dev
